import { type FeatureSpec, FeatureTarget } from "../types";

// ### ユニット強化関連特殊能力
export const FEATURES_U_99_OTHER = {
  // ### その他の特殊能力
  Uncontrollable: {
    name: "制御不可",
    target: FeatureTarget.Unit,
    effects: [],
    description: "常に暴走状態となりプレイヤーによる制御不可。",
    visible: false,
  },
  Unstable: {
    name: "不安定",
    target: FeatureTarget.Unit,
    effects: [],
    description: "ＨＰが最大値の1/4以下になると暴走する。",
  },
  SummonedUnit: {
    name: "召喚ユニット",
    target: FeatureTarget.Unit,
    effects: [],
    description: "召喚されたユニット。",
  },
  UnsummonCommandName: {
    name: "召喚解除コマンド名",
    target: FeatureTarget.Unit,
    effects: [],
    description: "召喚解除コマンドの名称を変更。",
    visible: false,
  },
  UntransformCommandName: {
    name: "変身解除コマンド名",
    target: FeatureTarget.Unit,
    effects: [],
    description: "変身解除コマンドの名称を変更。",
    visible: false,
  },
  SquadUnit: {
    name: "部隊ユニット",
    target: FeatureTarget.Unit,
    effects: [],
    description: "複数のユニットによって構成された部隊ユニット。",
  },
  Domination: {
    name: "支配",
    target: FeatureTarget.Unit,
    effects: [],
    description: "破壊時に支配対象のユニットも同時に破壊。",
  },
  CannotDefend: {
    name: "防御不可",
    target: FeatureTarget.Unit,
    effects: [],
    description: "攻撃を受けた際に防御運動を取ることが出来ない。",
  },
  CannotEvade: {
    name: "回避不可",
    target: FeatureTarget.Unit,
    effects: [],
    description: "攻撃を受けた際に回避運動を取ることが出来ない。",
  },
  SinglePilot: {
    name: "１人乗り可能",
    target: FeatureTarget.Unit,
    effects: [],
    description: "パイロットが不足していても出撃可能。",
    visible: false,
  },
  HasItem: {
    name: "アイテム所有",
    target: FeatureTarget.Unit,
    effects: [],
    description: "盗属性攻撃で盗めるアイテムを指定。",
    visible: false,
  },
  HasRareItem: {
    name: "レアアイテム所有",
    target: FeatureTarget.Unit,
    effects: [],
    description: "盗属性攻撃で1/8の確率で盗めるレアアイテムを指定。",
    visible: false,
  },
  LearnableSkill: {
    name: "ラーニング可能技",
    target: FeatureTarget.Unit,
    effects: [],
    description: "習属性攻撃で習得可能な技を指定。",
    visible: false,
  },
  TerrainUnit: {
    name: "地形ユニット",
    target: FeatureTarget.Unit,
    effects: [],
    description: "地形として扱われるユニット。",
    visible: false,
  },
  Invisible: {
    name: "非表示",
    target: FeatureTarget.Unit,
    effects: [],
    description: "ユニット画像を非表示にする。",
    visible: false,
  },
  RequiredSkill: {
    name: "必要技能",
    target: FeatureTarget.Unit,
    effects: [],
    description: "形態使用に必要な技能を指定。",
    visible: false,
  },
  UnnecessarySkill: {
    name: "不必要技能",
    target: FeatureTarget.Unit,
    effects: [],
    description: "形態使用不可となる技能を指定。",
    visible: false,
  },
  BattleAnimation: {
    name: "戦闘アニメ",
    target: FeatureTarget.Unit,
    effects: [],
    description: "戦闘アニメデータの検索名称を指定。",
    visible: false,
  },
  SpecialEffect: {
    name: "特殊効果",
    target: FeatureTarget.Unit,
    effects: [],
    description: "特殊効果データの検索名称を指定。",
    visible: false,
  },
  MessageClass: {
    name: "メッセージクラス",
    target: FeatureTarget.Unit,
    effects: [],
    description: "メッセージデータの検索クラス名を指定。",
    visible: false,
  },
  Term: {
    name: "用語名",
    target: FeatureTarget.Unit,
    effects: [],
    description: "各種用語の表示名称を変更。",
    visible: false,
  },
} as const satisfies Record<string, FeatureSpec>;
